apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  ## Name of the helm installation. 
  ## Same value used on "helm install [NAME]" command.
  name: crossplane
  namespace: flux-system
spec:
  ## Interval that you want to apply the lastest config in case new version is available.
  interval: 5m0s 
  chart:
    spec:
      ## Chart field must be the name of the helmchart. 
      ## Same value used on "helm install [NAME] [CHART]" command.
      chart: crossplane-stable/crossplane 
      ## Version field must be the chart version you want to install
      ## Same value used on "--version" parameter.
      version: '1.*'
      ## SourceRef must match the same name used in the helmrepository.yml file
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
  install:
    createNamespace: true
  targetNamespace: crossplane-system
